# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

resources:
- repo: self

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  repository: 'walmartpayment'
  namespace: 'walmartdev'
  k8sconnection: 'kubewalmartdev'
  imagePullSecret: 'test'

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'ACRDocker'
          repository: '$(repository)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            latest
            $(Build.BuildNumber)

      - task: PublishPipelineArtifact@1
        inputs:
          artifactName: 'manifests'
          path: 'manifests'

  