apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: mynamespace
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: mynamespace
roleRef:
  kind: Role
  name: my-role   # Replace with the name of the Role to be bound
  apiGroup: rbac.authorization.k8s.io
