apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
  namespace: mynamespace
rules:
  - apiGroups: [""] # Empty string indicates core API group
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
